### ISSUE TITLE
User redirect from select membership when not affiliated

### ISSUE THREAD

**Issue by bmiller501** [501works/hai-registration#8]
When a user is not affiliated with an organization they should not be able to buy an org membership, instead, they should be prompted to affiliate with an org which would take them to the select org page.

**Comment by bmiller501** [comment]
requires testing and review

**Comment by grever501** [comment]
This seems to work BUT - when you get to the affiliate company page - it only seems to present only companies.   So not sure if this is working ocmpeltely   

Record used is

mpetest+01-UC7B-03@gmail.com
MPETEST01 

All companies present on this page say they are members  I have not checked in the DB but if you go thru them.. they give you the req to affilate with that company

![Member companies only 2](https://user-images.githubusercontent.com/65407253/89571304-6e8e4b80-d7f5-11ea-8c08-d7c4c550ecc5.PNG)
![Member companies only](https://user-images.githubusercontent.com/65407253/89571305-6e8e4b80-d7f5-11ea-953f-9988bc2f9f3a.PNG)

**Comment by grever501** [comment]
Intial issue is reolved - us
![Issue 8 Verified](https://user-images.githubusercontent.com/65407253/89581947-cdf45780-d805-11ea-8d3c-7da14f76eb59.PNG)
ing record above user was prompted to affiliated with an org.
